upgrading_to_fusion:
  target: dev
  outputs:
    dev:
      type: snowflake
      threads: 16
      account: XETOHTP-BT48000
      user: gcuesta
      database: snowflake_learning_db
      warehouse: compute_wh
      schema: dbt_trouze
      password: Mestizorayna25???
